### ISSUE TITLE
Are you using this project?

### ISSUE THREAD

**Issue by Jiang1206** [SJTUwbl/MaCA#1]
Many parts of the original project cannot be changed. I would like to know what changes have you made compared to the original code

**Comment by SJTUwbl** [comment]
改动了雷达部分，去掉了干扰机的作用

**Comment by Jiang1206** [comment]
源码好多地方不是加密了吗？你怎么做到的？留个联系方式交流下可以不

**Comment by SJTUwbl** [comment]
> 源码好多地方不是加密了吗？你怎么做到的？留个联系方式交流下可以不
我按照他的功能，大体复现了出来，个别地方与源码不太一样。可以加我微信详细交流：May-Thirtieth

**Comment by lilingyu1024** [comment]
您好，我是本科生第一次接触强化学习，请问能够留下联系方式请教您一些问题么

**Comment by SJTUwbl** [comment]
> 您好，我是本科生第一次接触强化学习，请问能够留下联系方式请教您一些问题么

QQ: 1010517071
