### ISSUE TITLE
您好，求教！

### ISSUE THREAD

**Issue by CharlesPuth** [SJTUwbl/MaCA#2]
学长您好，我的毕设想使用MaCA平台进行开发，但是无奈加密部分都在最核心的地方让我相对无从下手。想请问您一下，您这个仓库是增加了别的决策算法吗？能否提供一些修改的思路？抱歉打扰，期待您的回复！ @SJTUwbl

**Comment by SJTUwbl** [comment]
很抱歉刚看到这条信息，这份代码将部分加密的代码按照自己的理解实现了出来，其中雷达和干扰机这一部分由于太复杂，我就没有去实现。

**Comment by CharlesPuth** [comment]
好吧，能进行这样的实现您太厉害啦，膜拜！还想请教一下，您提出的airc_homo_rule是基于什么算法写出还是您自己提出的规则，想了解一下您的想法，因为最近导师要求研究一下平台但是因为加密原因有效信息获取很匮乏，感谢回复！

**Comment by CharlesPuth** [comment]
@SJTUwbl

**Comment by SJTUwbl** [comment]
airc_homo_rule是基于《Efﬁcient Training Techniques forMulti-agent Reinforcement Learning inCombat Tasks》文章中的想法写的。

**Comment by CharlesPuth** [comment]
太感谢您了！感谢您的慷慨指教！我还只是一个刚刚进入多智能体强化学习领域的初学者，您对我提供的这些帮助太重要啦。晚辈冒昧想要一下您的常用邮箱联系方式，以后向您进行一些学术研究上的交流和指教。但是这里是公开场景您可能不太方便，我的个人邮箱是1452380548cl@gmail.com，如果有幸请您发一封邮件给晚辈，感谢您的指教！ @SJTUwbl
